development:
  host: localhost
  database: organizer_rtlong_com_development

test:
  host: localhost
  database: organizer_rtlong_com_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOLAB_URI'] %>