# Generated by cucumber_scaffold - http://github.com/andyw8/cucumber_scaffold

Feature: Manage tasks
  In order to [goal]
  [stakeholder]
  wants [behaviour]

    Scenario: List all tasks
      Given the following tasks:
        | name | description | importance | urgency | color |
        | name 1 | description 1 | 11 | 11 | 11 |
        | name 2 | description 2 | 12 | 12 | 12 |
        | name 3 | description 3 | 13 | 13 | 13 |
      When I go to the tasks page
      Then I should see the following tasks:
        | Name | Description | Importance | Urgency | Color |
        | name 1 | description 1 | 11 | 11 | 11 |
        | name 2 | description 2 | 12 | 12 | 12 |
        | name 3 | description 3 | 13 | 13 | 13 |
      And the heading should be "Listing tasks"


    Scenario: View a task
      Given the following tasks:
        | name | description | importance | urgency | color |
        | name 1 | description 1 | 11 | 11 | 11 |
        | name 2 | description 2 | 12 | 12 | 12 |
        | name 3 | description 3 | 13 | 13 | 13 |
      When I go to the tasks page
      And I click "Show" in the 2nd row
      Then I should see the following task:
        | Name: | name 2 |
        | Description: | description 2 |
        | Importance: | 12 |
        | Urgency: | 12 |
        | Color: | 12 |

      When I follow "Back"

      Then I should be on the tasks page

    Scenario: Edit a task
      Given the following task:
        | name | name 10 |
        | description | description 10 |
        | importance | 20 |
        | urgency | 20 |
        | color | 20 |
      When I go to the page for that task
      And I follow "Edit"
      Then I should see the following form field values:
        | Name | name 10 |
        | Description | description 10 |
        | Importance | 20 |
        | Urgency | 20 |
        | Color | 20 |
      Then the heading should be "Editing task"

      When I follow "Show"
      Then I should be on the page for that task

    Scenario: Delete a task via the index page
      Given the following tasks:
        | name | description | importance | urgency | color |
        | name 1 | description 1 | 11 | 11 | 11 |
        | name 2 | description 2 | 12 | 12 | 12 |
        | name 3 | description 3 | 13 | 13 | 13 |
      When I go to the tasks page
      And I click "Destroy" in the 2nd row
      Then I should see the following tasks:
        | Name | Description | Importance | Urgency | Color |
        | name 1 | description 1 | 11 | 11 | 11 |
        | name 3 | description 3 | 13 | 13 | 13 |
      And I should be on the tasks page


    Scenario: New task page
      Given I am on the tasks page
      When I follow "New Task"
      Then I should be on the new task page

      When I follow "Back"
      Then I should be on the tasks page

    Scenario: Create a new task
      Pending
      # Given I am on the new task page
      # When I fill in the form with:
      #   | Name | name 10 |
        # | Description | description 10 |
        # | Importance | 20 |
        # | Urgency | 20 |
        # | Color | 20 |
      # And I press "Create"
      # Then I should see "Task was successfully created."
      # And I should see the following task:
      #   | Name: | name 10 |
        # | Description: | description 10 |
        # | Importance: | 20 |
        # | Urgency: | 20 |
        # | Color: | 20 |

    Scenario: Attempt to create a new task with invalid input
      Pending
      # You should use this scenario as the basis for scenarios involving ActiveRecord validations, or delete it if it's not required
      # Given I am on the new task page
      # When I fill in the form with:
      #   | Name | name 10 |
        # | Description | description 10 |
        # | Importance | 20 |
        # | Urgency | 20 |
        # | Color | 20 |
      # And I press "Create"
      # Then I should see "1 error prohibited this task from being saved:"
      #
      # [You should add checks for specific errors here. It may be appropriate to add extra scenarios.]
      #
      # And I should see the following form field values:
      #   | Name | name 10 |
        # | Description | description 10 |
        # | Importance | 20 |
        # | Urgency | 20 |
        # | Color | 20 |

    Scenario: Attempt to update a task with invalid input
      Pending
      # You should use this scenario as the basis for scenarios involving ActiveRecord validations, or delete it if it's not required
      # Given a task exists
      # When I go to the edit page for that task
      # And I fill in the form with:
      #   | Name | name 10 |
        # | Description | description 10 |
        # | Importance | 20 |
        # | Urgency | 20 |
        # | Color | 20 |
      # And I press "Update"
      # Then I should see "1 error prohibited this task from being saved:"
      #
      # [You should add checks for specific errors here. It may be appropriate to add extra scenarios.]
      #
      # And I should see the following form field values:
      #   | Name | name 10 |
        # | Description | description 10 |
        # | Importance | 20 |
        # | Urgency | 20 |
        # | Color | 20 |

    Scenario: Update a task
      Given the following task:
        | name | name 10 |
        | description | description 10 |
        | importance | 20 |
        | urgency | 20 |
        | color | 20 |
      When I go to the edit page for that task
      And I fill in the form with:
        | Name | name 10 updated |
        | Description | description 10 updated |
        | Importance | -20 |
        | Urgency | -20 |
        | Color | -20 |
      And I press "Update"
      Then I should be on the page for that task
      And I should see "Task was successfully updated."
      And I should see the following task:
        | Name: | name 10 updated |
        | Description: | description 10 updated |
        | Importance: | -20 |
        | Urgency: | -20 |
        | Color: | -20 |

    Scenario: Navigate from tasks page to the edit task page
      Given the following tasks:
        | name | description | importance | urgency | color |
        | name 1 | description 1 | 11 | 11 | 11 |
        | name 2 | description 2 | 12 | 12 | 12 |
        | name 3 | description 3 | 13 | 13 | 13 |
      When I go to the tasks page
      And I click "Edit" in the 2nd row
      Then I should be on the edit page for the 2nd task

    Scenario: Navigate from edit task page to the tasks page
      Given a task exists
      When I go to the edit page for that task
      And I follow "Back"
      Then I should be on the tasks page